package com.cisco.ca.cstg.pdi.pojos.objectFactory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;

// Generated Nov 11, 2014 10:41:23 AM by Hibernate Tools 4.0.0

/**
 * Fabricbhvlan generated by hbm2java
 */

@XmlRootElement(name = "fabricBHVlan")
@XmlAccessorType(XmlAccessType.FIELD)
public class Fabricbhvlan implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7935948136572918979L;
	private int primaryKey;
	private Fabricfcestccloud fabricfcestccloud;
	
	@XmlAttribute(name = "policyOwner")
	private String policyOwner;
	
	@XmlAttribute(name = "sharing")
	private String sharing;
	
	@XmlAttribute(name = "pubNwName")
	private String pubNwName;
	
	@XmlAttribute(name = "name")
	private String name;
	
	@XmlAttribute(name = "id")
	private String id;

	public Fabricbhvlan() {
	}

	public Fabricbhvlan(int primaryKey, Fabricfcestccloud fabricfcestccloud) {
		this.primaryKey = primaryKey;
		this.fabricfcestccloud = fabricfcestccloud;
	}

	public Fabricbhvlan(int primaryKey, Fabricfcestccloud fabricfcestccloud,
			String policyOwner, String sharing, String pubNwName, String name,
			String id) {
		this.primaryKey = primaryKey;
		this.fabricfcestccloud = fabricfcestccloud;
		this.policyOwner = policyOwner;
		this.sharing = sharing;
		this.pubNwName = pubNwName;
		this.name = name;
		this.id = id;
	}

	public int getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(int primaryKey) {
		this.primaryKey = primaryKey;
	}

	public Fabricfcestccloud getFabricfcestccloud() {
		return this.fabricfcestccloud;
	}

	public void setFabricfcestccloud(Fabricfcestccloud fabricfcestccloud) {
		this.fabricfcestccloud = fabricfcestccloud;
	}

	public String getPolicyOwner() {
		return this.policyOwner;
	}

	public void setPolicyOwner(String policyOwner) {
		this.policyOwner = policyOwner;
	}

	public String getSharing() {
		return this.sharing;
	}

	public void setSharing(String sharing) {
		this.sharing = sharing;
	}

	public String getPubNwName() {
		return this.pubNwName;
	}

	public void setPubNwName(String pubNwName) {
		this.pubNwName = pubNwName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
