package com.cisco.ca.cstg.pdi.pojos.objectFactory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

// Generated Nov 11, 2014 10:41:23 AM by Hibernate Tools 4.0.0

/**
 * Statsthresholdpolicy generated by hbm2java
 */

@XmlType(name = "statsThresholdPolicy")
@XmlAccessorType(XmlAccessType.FIELD)
public class Statsthresholdpolicy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3805475590818482629L;
	private int primaryKey;
	private Fabricsancloud fabricsancloud;
	private Fabriclancloud fabriclancloud;
	private Fabricethestccloud fabricethestccloud;
	private Fabricdcesrv fabricdcesrv;
	private Fabricfcestccloud fabricfcestccloud;
	
	@XmlAttribute(name = "policyOwner")
	private String policyOwner;
	
	@XmlAttribute(name = "descr")
	private String descr;
	
	@XmlAttribute(name = "name")
	private String name;

	public Statsthresholdpolicy() {
	}

	public Statsthresholdpolicy(int primaryKey, Fabricsancloud fabricsancloud,
			Fabriclancloud fabriclancloud,
			Fabricethestccloud fabricethestccloud, Fabricdcesrv fabricdcesrv,
			Fabricfcestccloud fabricfcestccloud) {
		this.primaryKey = primaryKey;
		this.fabricsancloud = fabricsancloud;
		this.fabriclancloud = fabriclancloud;
		this.fabricethestccloud = fabricethestccloud;
		this.fabricdcesrv = fabricdcesrv;
		this.fabricfcestccloud = fabricfcestccloud;
	}

	public Statsthresholdpolicy(int primaryKey, Fabricsancloud fabricsancloud,
			Fabriclancloud fabriclancloud,
			Fabricethestccloud fabricethestccloud, Fabricdcesrv fabricdcesrv,
			Fabricfcestccloud fabricfcestccloud, String policyOwner,
			String descr, String name) {
		this.primaryKey = primaryKey;
		this.fabricsancloud = fabricsancloud;
		this.fabriclancloud = fabriclancloud;
		this.fabricethestccloud = fabricethestccloud;
		this.fabricdcesrv = fabricdcesrv;
		this.fabricfcestccloud = fabricfcestccloud;
		this.policyOwner = policyOwner;
		this.descr = descr;
		this.name = name;
	}

	public int getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(int primaryKey) {
		this.primaryKey = primaryKey;
	}

	public Fabricsancloud getFabricsancloud() {
		return this.fabricsancloud;
	}

	public void setFabricsancloud(Fabricsancloud fabricsancloud) {
		this.fabricsancloud = fabricsancloud;
	}

	public Fabriclancloud getFabriclancloud() {
		return this.fabriclancloud;
	}

	public void setFabriclancloud(Fabriclancloud fabriclancloud) {
		this.fabriclancloud = fabriclancloud;
	}

	public Fabricethestccloud getFabricethestccloud() {
		return this.fabricethestccloud;
	}

	public void setFabricethestccloud(Fabricethestccloud fabricethestccloud) {
		this.fabricethestccloud = fabricethestccloud;
	}

	public Fabricdcesrv getFabricdcesrv() {
		return this.fabricdcesrv;
	}

	public void setFabricdcesrv(Fabricdcesrv fabricdcesrv) {
		this.fabricdcesrv = fabricdcesrv;
	}

	public Fabricfcestccloud getFabricfcestccloud() {
		return this.fabricfcestccloud;
	}

	public void setFabricfcestccloud(Fabricfcestccloud fabricfcestccloud) {
		this.fabricfcestccloud = fabricfcestccloud;
	}

	public String getPolicyOwner() {
		return this.policyOwner;
	}

	public void setPolicyOwner(String policyOwner) {
		this.policyOwner = policyOwner;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
