package com.cisco.ca.cstg.pdi.pojos.objectFactory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

// Generated Nov 11, 2014 10:41:23 AM by Hibernate Tools 4.0.0


/**
 * Toproot generated by hbm2java
 */
@XmlRootElement(name="topRoot") 
@XmlAccessorType(XmlAccessType.FIELD)
public class Toproot implements java.io.Serializable {

	private static final long serialVersionUID = 5506080956782597915L;
	private int primaryKey;
	private Topsystem topSystem;
	private Orgorg orgOrg;
	private Fabricep fabricEp;
	private Callhomeep callhomeEp;

	public Toproot() {
	}

	public Toproot(int primaryKey) {
		this.primaryKey = primaryKey;
	}

	public Toproot(int primaryKey, Topsystem topsystems, Orgorg orgorgs, Fabricep fabriceps, Callhomeep callhomeEp) {
		this.primaryKey = primaryKey;
		this.topSystem = topsystems;
		this.orgOrg = orgorgs;
		this.fabricEp = fabriceps;
		this.callhomeEp = callhomeEp;
	}

	public int getPrimaryKey() {
		return this.primaryKey;
	}

	public void setPrimaryKey(int primaryKey) {
		this.primaryKey = primaryKey;
	}
	
	public Topsystem getTopSystem() {
		return topSystem;
	}

	public void setTopSystem(Topsystem topSystem) {
		this.topSystem = topSystem;
	}

	public Orgorg getOrgOrg() {
		return orgOrg;
	}

	public void setOrgOrg(Orgorg orgOrg) {
		this.orgOrg = orgOrg;
	}

	public Fabricep getFabricEp() {
		return fabricEp;
	}

	public void setFabricEp(Fabricep fabricEp) {
		this.fabricEp = fabricEp;
	}

	public Callhomeep getCallhomeEp() {
		return callhomeEp;
	}

	public void setCallhomeEp(Callhomeep callhomeEp) {
		this.callhomeEp = callhomeEp;
	}
}
