package com.cisco.ca.cstg.pdi.pojos; 

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Configuration generated by hbm2java
 */
@Entity
@Table(name = "configuration")
public class Configuration implements java.io.Serializable {
	
	private static final long serialVersionUID = 2029325223656064651L;
	private Integer id;
	private ProjectDetails projectDetails;
	private String ipAddress;
	private String userName;
	private String password;
	private Boolean pingVerified;
	private Boolean pushStatus;
	private Boolean downloadConfigStatus;

	public Configuration() {
	}
	
	public Configuration(Integer id) {
		this.id = id;
	}	
	
	public Configuration(ServerDetails serverDetails) {
		this.projectDetails = serverDetails.getProjectDetails();
		this.ipAddress = serverDetails.getUrl();
		this.userName = serverDetails.getUserName();
		this.password = serverDetails.getEncryptedPassword();
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@Column(name = "ip_address", length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ping_verified")
	public Boolean getPingVerified() {
		return this.pingVerified;
	}

	public void setPingVerified(Boolean pingVerified) {
		this.pingVerified = pingVerified;
	}

	@Column(name = "push_status")
	public Boolean getPushStatus() {
		return this.pushStatus;
	}

	public void setPushStatus(Boolean pushStatus) {
		this.pushStatus = pushStatus;
	}

	@Column(name = "download_config_status")
	public Boolean getDownloadConfigStatus() {
		return this.downloadConfigStatus;
	}

	public void setDownloadConfigStatus(Boolean downloadConfigStatus) {
		this.downloadConfigStatus = downloadConfigStatus;
	}

}
