package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Arrays;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Infrastructure generated by hbm2java
 */
@Entity
@Table(name = "infrastructure")
public class Infrastructure implements java.io.Serializable {

	private static final long serialVersionUID = 2616535288463521495L;
	private Integer id;
	private ProjectDetails projectDetails;
	private ServerModel serverModel;
	private String softwareVersion;
	private String ioModule;
	private byte[] image;

	public Infrastructure() {
	}

	public Infrastructure(int id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "server_model")
	@Fetch(FetchMode.SELECT)
	public ServerModel getServerModel() {
		return this.serverModel;
	}

	public void setServerModel(ServerModel serverModel) {
		this.serverModel = serverModel;
	}

	@Column(name = "software_version", length = 45)
	public String getSoftwareVersion() {
		return this.softwareVersion;
	}

	public void setSoftwareVersion(String softwareVersion) {
		this.softwareVersion = softwareVersion;
	}

	@Column(name = "io_module", length = 45)
	public String getIoModule() {
		return this.ioModule;
	}

	public void setIoModule(String ioModule) {
		this.ioModule = ioModule;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] newImage) {
		this.image = image != null ? Arrays.copyOf(newImage, newImage.length)
				: new byte[0];
	}

}
