package com.cisco.ca.cstg.pdi.pojos;
// Generated Jun 30, 2015 2:59:45 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * LanConnectivityPolicy generated by hbm2java
 */
@Entity
@Table(name = "lan_connectivity_policy")
public class LanConnectivityPolicy implements java.io.Serializable {

	private static final long serialVersionUID = 3352452939088151058L;
	private Integer id;
	private ProjectDetails projectDetails;
	private Organizations organizations;
	private String name;
	private String description;
	private List<LanLcpVnicMapping> lanLcpVnicMappings = new ArrayList<LanLcpVnicMapping>();
	private List<ServersServiceProfileTemplate> serversServiceProfileTemplates = new ArrayList<ServersServiceProfileTemplate>(0);

	public LanConnectivityPolicy() {
	}
	
	
	public LanConnectivityPolicy(Integer id) {		
		this.id = id;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization")
	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "lanConnectivityPolicy")
	@Fetch(FetchMode.SELECT)
	public List<LanLcpVnicMapping> getLanLcpVnicMappings() {
		return this.lanLcpVnicMappings;
	}

	public void setLanLcpVnicMappings(List<LanLcpVnicMapping> lanLcpVnicMappings) {
		this.lanLcpVnicMappings = lanLcpVnicMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanConnectivityPolicy")
	public List<ServersServiceProfileTemplate> getServersServiceProfileTemplates() {
		return this.serversServiceProfileTemplates;
	}

	public void setServersServiceProfileTemplates(
			List<ServersServiceProfileTemplate> serversServiceProfileTemplates) {
		this.serversServiceProfileTemplates = serversServiceProfileTemplates;
	}

}
