package com.cisco.ca.cstg.pdi.pojos;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LanMgmtIppool generated by hbm2java
 */
@Entity
@Table(name = "lan_mgmt_ippool")
public class LanMgmtIppool implements java.io.Serializable {

	private static final long serialVersionUID = 8337129744597623941L;
	private Integer id;
	private ProjectDetails projectDetails;
	private Organizations organizations;
	private String name;
	private String description;
	private String fromAddress;
	private String toAddress;
	private String defaultGateway;
	private String subnetMask;
	private String dns;
	private String noOfAddresses;
	
	
	public LanMgmtIppool() {
	}
	
	public LanMgmtIppool(Integer id) {
		this.id = id;
	}

	public LanMgmtIppool(ProjectDetails projectDetails,
			Organizations organizations, String name, String description,
			String fromAddress, String toAddress, String defaultGateway,
			String subnetMask, String dns, String noOfAddresses) {
		this.projectDetails = projectDetails;
		this.organizations = organizations;
		this.name = name;
		this.description = description;
		this.fromAddress = fromAddress;
		this.toAddress = toAddress;
		this.defaultGateway = defaultGateway;
		this.subnetMask = subnetMask;
		this.dns = dns;
		this.noOfAddresses = noOfAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization")
	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	@Column(name = "ippool_name", length = 45)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "from_address", length = 45)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "to_address", length = 45)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@Column(name = "default_gateway", length = 45)
	public String getDefaultGateway() {
		return this.defaultGateway;
	}

	public void setDefaultGateway(String defaultGateway) {
		this.defaultGateway = defaultGateway;
	}

	@Column(name = "subnet_mask", length = 45)
	public String getSubnetMask() {
		return this.subnetMask;
	}

	public void setSubnetMask(String subnetMask) {
		this.subnetMask = subnetMask;
	}

	@Column(name = "dns", length = 45)
	public String getDns() {
		return this.dns;
	}

	public void setDns(String dns) {
		this.dns = dns;
	}
	
	@Transient
	public String getNoOfAddresses() {
		return noOfAddresses;
	}

	public void setNoOfAddresses(String noOfAddresses) {
		this.noOfAddresses = noOfAddresses;
	}
	
	
}
