package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * LanMacpool generated by hbm2java
 */
@Entity
@Table(name = "lan_macpool")
public class LanMacpool implements java.io.Serializable {

	private static final long serialVersionUID = -5960561137443955306L;
	private Integer id;
	private ProjectDetails projectDetails;
	private Organizations organizations;
	private String macpoolName;
	private String macpoolDescription;
	private String assignmentOrder;
	private String fromAddress;
	private String toAddress;
	private String noOfAddresses;
	private List<LanVnicTemplate> lanVnicTemplates = new ArrayList<LanVnicTemplate>(0);

	public LanMacpool() {
	}
	
	public LanMacpool(Integer id) {
		this.id = id;
	}

	public LanMacpool(ProjectDetails projectDetails,
			Organizations organizations, String macpoolName,
			String macpoolDescription, String assignmentOrder,
			String fromAddress, String toAddress,String noOfAddresses, List<LanVnicTemplate> lanVnicTemplates) {
		this.projectDetails = projectDetails;
		this.organizations = organizations;
		this.macpoolName = macpoolName;
		this.macpoolDescription = macpoolDescription;
		this.assignmentOrder = assignmentOrder;
		this.fromAddress = fromAddress;
		this.toAddress = toAddress;
		this.noOfAddresses = noOfAddresses;
		this.lanVnicTemplates = lanVnicTemplates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization")
	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	@Column(name = "macpool_name", length = 45)
	public String getMacpoolName() {
		return this.macpoolName;
	}

	public void setMacpoolName(String macpoolName) {
		this.macpoolName = macpoolName;
	}

	@Column(name = "macpool_description", length = 45)
	public String getMacpoolDescription() {
		return this.macpoolDescription;
	}

	public void setMacpoolDescription(String macpoolDescription) {
		this.macpoolDescription = macpoolDescription;
	}

	@Column(name = "assignmentOrder", length = 45)
	public String getAssignmentOrder() {
		return this.assignmentOrder;
	}

	public void setAssignmentOrder(String assignmentOrder) {
		this.assignmentOrder = assignmentOrder;
	}

	@Column(name = "from_address", length = 45)
	public String getFromAddress() {
		return this.fromAddress;
	}

	public void setFromAddress(String fromAddress) {
		this.fromAddress = fromAddress;
	}

	@Column(name = "to_address", length = 45)
	public String getToAddress() {
		return this.toAddress;
	}

	public void setToAddress(String toAddress) {
		this.toAddress = toAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanMacpool")
	public List<LanVnicTemplate> getLanVnicTemplates() {
		return this.lanVnicTemplates;
	}

	public void setLanVnicTemplates(List<LanVnicTemplate> lanVnicTemplates) {
		this.lanVnicTemplates = lanVnicTemplates;
	}
	
	@Transient
	public String getNoOfAddresses() {
		return noOfAddresses;
	}

	public void setNoOfAddresses(String noOfAddresses) {
		this.noOfAddresses = noOfAddresses;
	}		
}
