package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LanNetworkControlPolicy generated by hbm2java
 */
@Entity
@Table(name = "lan_network_control_policy")
public class LanNetworkControlPolicy implements java.io.Serializable {

	private static final long serialVersionUID = 7293017271950804613L;
	private Integer id;
	private ProjectDetails projectDetails;
	private Organizations organizations;
	private String ncpName;
	private String description;
	private String cdp;
	private String macRegisterMode;
	private String uplinkFailAction;
	private String forge;
	private List<LanVnicTemplate> lanVnicTemplates = new ArrayList<LanVnicTemplate>(0);

	public LanNetworkControlPolicy() {
	}
	
	public LanNetworkControlPolicy(Integer id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization")
	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	@Column(name = "ncp_name", length = 16)
	public String getNcpName() {
		return this.ncpName;
	}

	public void setNcpName(String ncpName) {
		this.ncpName = ncpName;
	}

	@Column(name = "description", length = 256)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cdp", length = 45)
	public String getCdp() {
		return this.cdp;
	}

	public void setCdp(String cdp) {
		this.cdp = cdp;
	}

	@Column(name = "mac_register_mode", length = 45)
	public String getMacRegisterMode() {
		return this.macRegisterMode;
	}

	public void setMacRegisterMode(String macRegisterMode) {
		this.macRegisterMode = macRegisterMode;
	}

	@Column(name = "uplink_fail_action", length = 45)
	public String getUplinkFailAction() {
		return this.uplinkFailAction;
	}

	public void setUplinkFailAction(String uplinkFailAction) {
		this.uplinkFailAction = uplinkFailAction;
	}

	@Column(name = "forge", length = 45)
	public String getForge() {
		return this.forge;
	}

	public void setForge(String forge) {
		this.forge = forge;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanNetworkControlPolicy")
	public List<LanVnicTemplate> getLanVnicTemplates() {
		return this.lanVnicTemplates;
	}

	public void setLanVnicTemplates(List<LanVnicTemplate> lanVnicTemplates) {
		this.lanVnicTemplates = lanVnicTemplates;
	}

}
