package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LanQosPolicy generated by hbm2java
 */
@Entity
@Table(name = "lan_qos_policy")
public class LanQosPolicy implements java.io.Serializable {

	private static final long serialVersionUID = -6589377829282174928L;
	private Integer id;
	private ProjectDetails projectDetails;
	private Organizations organizations;
	private String name;
	private String priority;
	private Integer burst;
	private String rate;
	private String hostControl;
	private List<SanVhbaTemplate> sanVhbaTemplates = new ArrayList<SanVhbaTemplate>(0);
	private List<LanVnicTemplate> lanVnicTemplates = new ArrayList<LanVnicTemplate>(0);

	public LanQosPolicy() {
	}
	
	public LanQosPolicy(Integer id) {
		this.id = id;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization")
	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "priority", length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "burst")
	public Integer getBurst() {
		return this.burst;
	}

	public void setBurst(Integer burst) {
		this.burst = burst;
	}

	@Column(name = "rate", length = 45)
	public String getRate() {
		return this.rate;
	}

	public void setRate(String rate) {
		this.rate = rate;
	}

	@Column(name = "host_control", length = 45)
	public String getHostControl() {
		return this.hostControl;
	}

	public void setHostControl(String hostControl) {
		this.hostControl = hostControl;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanQosPolicy")
	public List<SanVhbaTemplate> getSanVhbaTemplates() {
		return this.sanVhbaTemplates;
	}

	public void setSanVhbaTemplates(List<SanVhbaTemplate> sanVhbaTemplates) {
		this.sanVhbaTemplates = sanVhbaTemplates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanQosPolicy")
	public List<LanVnicTemplate> getLanVnicTemplates() {
		return this.lanVnicTemplates;
	}

	public void setLanVnicTemplates(List<LanVnicTemplate> lanVnicTemplates) {
		this.lanVnicTemplates = lanVnicTemplates;
	}

}
