package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * LanVnicTemplate generated by hbm2java
 */
@Entity
@Table(name = "lan_vnic_template")
public class LanVnicTemplate implements java.io.Serializable {

	private static final long serialVersionUID = -4864193175890465740L;
	private Integer id;
	private ProjectDetails projectDetails;
	private LanNetworkControlPolicy lanNetworkControlPolicy;
	private LanQosPolicy lanQosPolicy;
	private Organizations organizations;
	private LanMacpool lanMacpool;
	private String vnictName;
	private String description;
	private String switchId;
	private String target;
	private String templateType;
	private String osType;
	private List<LanVnicTemplateVlanMapping> lanVnictVlanMappings = new ArrayList<LanVnicTemplateVlanMapping>();
	private List<LanVnic> lanVnics = new ArrayList<LanVnic>(0);

	public LanVnicTemplate() {
	}
	
	public LanVnicTemplate(Integer id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "network_control_policy_id")
	public LanNetworkControlPolicy getLanNetworkControlPolicy() {
		return this.lanNetworkControlPolicy;
	}

	public void setLanNetworkControlPolicy(
			LanNetworkControlPolicy lanNetworkControlPolicy) {
		this.lanNetworkControlPolicy = lanNetworkControlPolicy;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "qos_policy_id")
	public LanQosPolicy getLanQosPolicy() {
		return this.lanQosPolicy;
	}

	public void setLanQosPolicy(LanQosPolicy lanQosPolicy) {
		this.lanQosPolicy = lanQosPolicy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "organization")
	public Organizations getOrganizations() {
		return this.organizations;
	}

	public void setOrganizations(Organizations organizations) {
		this.organizations = organizations;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "macpool_id")
	public LanMacpool getLanMacpool() {
		return this.lanMacpool;
	}

	public void setLanMacpool(LanMacpool lanMacpool) {
		this.lanMacpool = lanMacpool;
	}

	@Column(name = "vnict_name", length = 45)
	public String getVnictName() {
		return this.vnictName;
	}

	public void setVnictName(String vnictName) {
		this.vnictName = vnictName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "switch_id", length = 45)
	public String getSwitchId() {
		return this.switchId;
	}

	public void setSwitchId(String switchId) {
		this.switchId = switchId;
	}

	@Column(name = "target", length = 45)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "template_type", length = 45)
	public String getTemplateType() {
		return this.templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}

	@Column(name = "os_type", length = 45)
	public String getOsType() {
		return this.osType;
	}

	public void setOsType(String osType) {
		this.osType = osType;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "lanVnicTemplate")
	@Fetch(FetchMode.SELECT)
	public List<LanVnicTemplateVlanMapping> getLanVnictVlanMappings() {
		return this.lanVnictVlanMappings;
	}

	public void setLanVnictVlanMappings(List<LanVnicTemplateVlanMapping> lanVnictVlanMappings) {
		this.lanVnictVlanMappings = lanVnictVlanMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanVnicTemplate")
	public List<LanVnic> getLanVnics() {
		return this.lanVnics;
	}

	public void setLanVnics(List<LanVnic> lanVnics) {
		this.lanVnics = lanVnics;
	}

}
