package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LanVlan generated by hbm2java
 */
@Entity
@Table(name = "lan_vlan")
public class LanVlan implements java.io.Serializable {

	private static final long serialVersionUID = 2407449553953021859L;
	private Integer id;
	private ProjectDetails projectDetails;
	private String vlanName;
	private String description;
	private String vlanId;
	private Boolean vlanDefault;
	private List<LanVnicTemplateVlanMapping> lanVnictVlanMappings = new ArrayList<LanVnicTemplateVlanMapping>(0);

	public LanVlan() {
	}

	public LanVlan(Integer id) {
		this.id = id;
	}

	public LanVlan(ProjectDetails projectDetails, String vlanName,
			String description, String vlanId, Boolean vlanDefault,
			List<LanVnicTemplateVlanMapping> lanVnictVlanMappings) {
		this.projectDetails = projectDetails;
		this.vlanName = vlanName;
		this.description = description;
		this.vlanId = vlanId;
		this.vlanDefault = vlanDefault;
		this.lanVnictVlanMappings = lanVnictVlanMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@Column(name = "vlan_name", length = 45)
	public String getVlanName() {
		return this.vlanName;
	}

	public void setVlanName(String vlanName) {
		this.vlanName = vlanName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "vlan_id", length = 45)
	public String getVlanId() {
		return this.vlanId;
	}

	public void setVlanId(String vlanId) {
		this.vlanId = vlanId;
	}

	@Column(name = "vlan_default")
	public Boolean getVlanDefault() {
		return this.vlanDefault;
	}

	public void setVlanDefault(Boolean vlanDefault) {
		this.vlanDefault = vlanDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lanVlan")
	public List<LanVnicTemplateVlanMapping> getLanVnictVlanMappings() {
		return this.lanVnictVlanMappings;
	}

	public void setLanVnictVlanMappings(List<LanVnicTemplateVlanMapping> lanVnictVlanMappings) {
		this.lanVnictVlanMappings = lanVnictVlanMappings;
	}

}
