package com.cisco.ca.cstg.pdi.pojos;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * LanVnic generated by hbm2java
 */
@Entity
@Table(name = "lan_vnic")
public class LanVnic implements java.io.Serializable {

	private static final long serialVersionUID = -4049203755550361455L;
	private Integer id;
	private ProjectDetails projectDetails;
	private LanEthernetAdapterPolicies lanEthernetAdapterPolicies;
	private LanVnicTemplate lanVnicTemplate;
	private String name;
	
	public LanVnic() {
	}
		
	public LanVnic(Integer id) {		
		this.id = id;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "lan_ethernet_adapter_policy_id")
	public LanEthernetAdapterPolicies getLanEthernetAdapterPolicies() {
		return this.lanEthernetAdapterPolicies;
	}

	public void setLanEthernetAdapterPolicies(
			LanEthernetAdapterPolicies lanEthernetAdapterPolicies) {
		this.lanEthernetAdapterPolicies = lanEthernetAdapterPolicies;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@Fetch(FetchMode.SELECT)
	@JoinColumn(name = "lan_vnic_template_id")
	public LanVnicTemplate getLanVnicTemplate() {
		return this.lanVnicTemplate;
	}

	public void setLanVnicTemplate(LanVnicTemplate lanVnicTemplate) {
		this.lanVnicTemplate = lanVnicTemplate;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}	

}
