package com.cisco.ca.cstg.pdi.pojos;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * License generated by hbm2java
 */
@Entity
@Table(name = "license")
public class License implements java.io.Serializable {

	private static final long serialVersionUID = -7331267811098232336L;
	private Integer id;
	private String name;
	private String description;
	private String assessorId;
	private String assessorName;
	private String assessorType;
	private String purpose;
	private Date creationDate;
	private Date targetStartTime;
	private Date targetEndTime;
	private String theatre;
	private String customerName;
	private String customerBusiness;
	private String customerDescription;
	private String customerVertical;
	private String asPid;
	private String site;
	private String createdby;
	private String downloadedby;
	private String siteId;
	private String serviceType;

	public License() {
	}
	
	public License(Integer id) {
		this.id = id;
	}		

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "assessor_id", length = 45)
	public String getAssessorId() {
		return this.assessorId;
	}

	public void setAssessorId(String assessorId) {
		this.assessorId = assessorId;
	}

	@Column(name = "assessor_name", length = 45)
	public String getAssessorName() {
		return this.assessorName;
	}

	public void setAssessorName(String assessorName) {
		this.assessorName = assessorName;
	}

	@Column(name = "assessor_type", length = 45)
	public String getAssessorType() {
		return this.assessorType;
	}

	public void setAssessorType(String assessorType) {
		this.assessorType = assessorType;
	}

	@Column(name = "purpose", length = 45)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "target_start_time", length = 19)
	public Date getTargetStartTime() {
		return this.targetStartTime;
	}

	public void setTargetStartTime(Date targetStartTime) {
		this.targetStartTime = targetStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "target_end_time", length = 19)
	public Date getTargetEndTime() {
		return this.targetEndTime;
	}

	public void setTargetEndTime(Date targetEndTime) {
		this.targetEndTime = targetEndTime;
	}

	@Column(name = "theatre", length = 45)
	public String getTheatre() {
		return this.theatre;
	}

	public void setTheatre(String theatre) {
		this.theatre = theatre;
	}

	@Column(name = "customer_name", length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_business", length = 45)
	public String getCustomerBusiness() {
		return this.customerBusiness;
	}

	public void setCustomerBusiness(String customerBusiness) {
		this.customerBusiness = customerBusiness;
	}

	@Column(name = "customer_description", length = 45)
	public String getCustomerDescription() {
		return this.customerDescription;
	}

	public void setCustomerDescription(String customerDescription) {
		this.customerDescription = customerDescription;
	}

	@Column(name = "customer_vertical", length = 45)
	public String getCustomerVertical() {
		return this.customerVertical;
	}

	public void setCustomerVertical(String customerVertical) {
		this.customerVertical = customerVertical;
	}

	@Column(name = "as_pid", length = 45)
	public String getAsPid() {
		return this.asPid;
	}

	public void setAsPid(String asPid) {
		this.asPid = asPid;
	}

	@Column(name = "site", length = 45)
	public String getSite() {
		return this.site;
	}

	public void setSite(String site) {
		this.site = site;
	}

	@Column(name = "createdby", length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Column(name = "downloadedby", length = 45)
	public String getDownloadedby() {
		return this.downloadedby;
	}

	public void setDownloadedby(String downloadedby) {
		this.downloadedby = downloadedby;
	}

	@Column(name = "site_id", length = 45)
	public String getSiteId() {
		return this.siteId;
	}

	public void setSiteId(String siteId) {
		this.siteId = siteId;
	}

	@Column(name = "SERVICE_TYPE", length = 45)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

	public void clearProjectDetails() {
		id = 1;
		name = "";
		description = "";
		assessorId = "";
		assessorName = "";
		assessorType = "";
		purpose = "";
		theatre = "";
		customerName = "";
		customerDescription = "";
		customerBusiness = "";
		customerVertical = "";
		asPid = "";
		site = "";
		createdby = "";
		downloadedby = "";
		siteId = "";
	}	
}