package com.cisco.ca.cstg.pdi.pojos;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServerModel generated by hbm2java
 */
@Entity
@Table(name = "server_model")
public class ServerModel implements java.io.Serializable {

	private static final long serialVersionUID = 1548459312373647880L;
	private int id;
	private String description;
	private String softwareVersion;
	private List<Infrastructure> infrastructures = new ArrayList<Infrastructure>(0);

	public ServerModel() {
	}

	public ServerModel(int id) {
		this.id = id;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "software_version", length = 45)
	public String getSoftwareVersion() {
		return this.softwareVersion;
	}

	public void setSoftwareVersion(String softwareVersion) {
		this.softwareVersion = softwareVersion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serverModel")
	public List<Infrastructure> getInfrastructures() {
		return this.infrastructures;
	}

	public void setInfrastructures(List<Infrastructure> infrastructures) {
		this.infrastructures = infrastructures;
	}

}
